language: python
services:
  - docker
install:
  - make deps
script:
  - make lint
  - make test
#after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: NAZWA TWOJEJ APLIKACJI
  api_key: ${HEROKU_API_KEY}
